package com.kirolak;

// Generated 30-nov-2007 8:26:55 by Hibernate Tools 3.2.0.CR1

import java.util.Date;

/**
 * Match generated by hbm2java
 */
public class Match extends KirolakObject
{

	private Round round;
	private Team homeTeam;
	private Team visitingTeam;
	private Short homeTeamScore;
	private Short visitingTeamScore;
	private Byte matchStatus;
	private Date dayTime;
	private Date updated;

	public Match()
	{
		this.id = -1;
	}

	public Match(int id)
	{
		this.id = id;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public Round getRound()
	{
		return this.round;
	}

	public void setRound(Round round)
	{
		this.round = round;
	}

	public Group getGroup()
	{
		return this.round.getGroup();
	}

	public void setGroup(Group group)
	{
		this.round.setGroup(group);
	}

	public Team getHomeTeam()
	{
		return this.homeTeam;
	}

	public void setHomeTeamId(Team homeTeam)
	{
		this.homeTeam = homeTeam;
	}

	public Team getVisitingTeam()
	{
		return this.visitingTeam;
	}

	public void setVisitingTeamId(Team visitingTeam)
	{
		this.visitingTeam = visitingTeam;
	}

	public Short getHomeTeamScore()
	{
		return this.homeTeamScore;
	}

	public void setHomeTeamScore(Short homeTeamScore)
	{
		this.homeTeamScore = homeTeamScore;
	}

	public Short getVisitingTeamScore()
	{
		return this.visitingTeamScore;
	}

	public void setVisitingTeamScore(Short visitingTeamScore)
	{
		this.visitingTeamScore = visitingTeamScore;
	}


	public Byte getMatchStatus()
	{
		return matchStatus;
	}

	public void setMatchStatus(Byte matchStatus)
	{
		this.matchStatus = matchStatus;
	}

	public Date getDayTime()
	{
		return this.dayTime;
	}

	public void setScheduled(Date dayTime)
	{
		this.dayTime = dayTime;
	}

	public Date getUpdated()
	{
		return updated;
	}

	public void setUpdated(Date updated)
	{
		this.updated = updated;
	}

	public void setHomeTeam(Team homeTeam)
	{
		this.homeTeam = homeTeam;
	}

	public void setVisitingTeam(Team visitingTeam)
	{
		this.visitingTeam = visitingTeam;
	}

	public void setDayTime(Date dayTime)
	{
		this.dayTime = dayTime;
	}

}
