package com.kirolak;


// Generated 30-nov-2007 8:26:55 by Hibernate Tools 3.2.0.CR1

/**
 * Sport generated by hbm2java
 */
public class MatchStatus extends LocalizedListItem
{


	public MatchStatus()
	{
		
	}
}
