package com.kirolak;

import java.util.List;

// Generated 30-nov-2007 8:26:55 by Hibernate Tools 3.2.0.CR1

/**
 * Standing generated by hbm2java
 */
public class Standing implements java.io.Serializable
{

	private StandingId id;
	private Short games = 0;
	private Short gamesHome = 0;
	private Short gamesVisiting = 0;
	private Short wonGames = 0;
	private Short wonHome = 0;
	private Short wonVisiting = 0;
	private Short drawnGames = 0;
	private Short drawnHome = 0;
	private Short drawnVisiting = 0;
	private Short lostGames = 0;
	private Short lostHome = 0;
	private Short lostVisiting = 0;
	private Integer scoreTotal = 0;
	private Integer scoreHome = 0;
	private Integer scoreVisiting = 0;
	private Integer scoreAgainstTotal = 0;
	private Integer scoreAgainstHome = 0;
	private Integer scoreAgainstVisiting = 0;
	private Integer teamPoints = 0;
	private Integer homePoints = 0;
	private Integer visitingPoints = 0;
	private Short tieBreakPosition = 0;

	public Standing()
	{
	}

	public Standing(StandingId id)
	{
		this.id = id;
	}

	public Standing(StandingId id, Short games, Short gamesHome, Short gamesVisiting, Short wonGames, Short wonHome, Short wonVisiting,
			Short drawnGames, Short drawnHome, Short drawnVisiting, Short lostGames, Short lostHome, Short lostVisiting, Integer scoreTotal,
			Integer scoreHome, Integer scoreVisiting, Integer scoreAgainstTotal, Integer scoreAgainstHome, Integer scoreAgainstVisiting,
			Integer teamPoints, Integer homePoints, Integer visitingPoints, Short tieBreakPosition)
	{
		this.id = id;
		this.games = games;
		this.gamesHome = gamesHome;
		this.gamesVisiting = gamesVisiting;
		this.wonGames = wonGames;
		this.wonHome = wonHome;
		this.wonVisiting = wonVisiting;
		this.drawnGames = drawnGames;
		this.drawnHome = drawnHome;
		this.drawnVisiting = drawnVisiting;
		this.lostGames = lostGames;
		this.lostHome = lostHome;
		this.lostVisiting = lostVisiting;
		this.scoreTotal = scoreTotal;
		this.scoreHome = scoreHome;
		this.scoreVisiting = scoreVisiting;
		this.scoreAgainstTotal = scoreAgainstTotal;
		this.scoreAgainstHome = scoreAgainstHome;
		this.scoreAgainstVisiting = scoreAgainstVisiting;
		this.teamPoints = teamPoints;
		this.homePoints = homePoints;
		this.visitingPoints = visitingPoints;
		this.tieBreakPosition = tieBreakPosition;
	}

	public StandingId getId()
	{
		return this.id;
	}

	public void setId(StandingId id)
	{
		this.id = id;
	}

	public Short getGames()
	{
		return this.games;
	}

	public void setGames(Short games)
	{
		this.games = games;
	}

	public Short getGamesHome()
	{
		return this.gamesHome;
	}

	public void setGamesHome(Short gamesHome)
	{
		this.gamesHome = gamesHome;
	}

	public Short getGamesVisiting()
	{
		return this.gamesVisiting;
	}

	public void setGamesVisiting(Short gamesVisiting)
	{
		this.gamesVisiting = gamesVisiting;
	}

	public Short getWonGames()
	{
		return this.wonGames;
	}

	public void setWonGames(Short wonGames)
	{
		this.wonGames = wonGames;
	}

	public Short getWonHome()
	{
		return this.wonHome;
	}

	public void setWonHome(Short wonHome)
	{
		this.wonHome = wonHome;
	}

	public Short getWonVisiting()
	{
		return this.wonVisiting;
	}

	public void setWonVisiting(Short wonVisiting)
	{
		this.wonVisiting = wonVisiting;
	}

	public Short getDrawnGames()
	{
		return this.drawnGames;
	}

	public void setDrawnGames(Short drawnGames)
	{
		this.drawnGames = drawnGames;
	}

	public Short getDrawnHome()
	{
		return this.drawnHome;
	}

	public void setDrawnHome(Short drawnHome)
	{
		this.drawnHome = drawnHome;
	}

	public Short getDrawnVisiting()
	{
		return this.drawnVisiting;
	}

	public void setDrawnVisiting(Short drawnVisiting)
	{
		this.drawnVisiting = drawnVisiting;
	}

	public Short getLostGames()
	{
		return this.lostGames;
	}

	public void setLostGames(Short lostGames)
	{
		this.lostGames = lostGames;
	}

	public Short getLostHome()
	{
		return this.lostHome;
	}

	public void setLostHome(Short lostHome)
	{
		this.lostHome = lostHome;
	}

	public Short getLostVisiting()
	{
		return this.lostVisiting;
	}

	public void setLostVisiting(Short lostVisiting)
	{
		this.lostVisiting = lostVisiting;
	}

	public Integer getScoreTotal()
	{
		return this.scoreTotal;
	}

	public void setScoreTotal(Integer scoreTotal)
	{
		this.scoreTotal = scoreTotal;
	}

	public Integer getScoreHome()
	{
		return this.scoreHome;
	}

	public void setScoreHome(Integer scoreHome)
	{
		this.scoreHome = scoreHome;
	}

	public Integer getScoreVisiting()
	{
		return this.scoreVisiting;
	}

	public void setScoreVisiting(Integer scoreVisiting)
	{
		this.scoreVisiting = scoreVisiting;
	}

	public Integer getScoreAgainstTotal()
	{
		return this.scoreAgainstTotal;
	}

	public void setScoreAgainstTotal(Integer scoreAgainstTotal)
	{
		this.scoreAgainstTotal = scoreAgainstTotal;
	}

	public Integer getScoreAgainstHome()
	{
		return this.scoreAgainstHome;
	}

	public void setScoreAgainstHome(Integer scoreAgainstHome)
	{
		this.scoreAgainstHome = scoreAgainstHome;
	}

	public Integer getScoreAgainstVisiting()
	{
		return this.scoreAgainstVisiting;
	}

	public void setScoreAgainstVisiting(Integer scoreAgainstVisiting)
	{
		this.scoreAgainstVisiting = scoreAgainstVisiting;
	}

	public Integer getTeamPoints()
	{
		return this.teamPoints;
	}

	public void setTeamPoints(Integer teamPoints)
	{
		this.teamPoints = teamPoints;
	}

	public Integer getHomePoints()
	{
		return this.homePoints;
	}

	public void setHomePoints(Integer homePoints)
	{
		this.homePoints = homePoints;
	}

	public Integer getVisitingPoints()
	{
		return this.visitingPoints;
	}

	public void setVisitingPoints(Integer visitingPoints)
	{
		this.visitingPoints = visitingPoints;
	}

	public Short getTieBreakPosition()
	{
		return this.tieBreakPosition;
	}

	public void setTieBreakPosition(Short tieBreakPosition)
	{
		this.tieBreakPosition = tieBreakPosition;
	}	
	
	public static void generate(Round round, Round lastUpdatedRound)
	{
		
	}
	
	public List<Standing> calculate(Round round)
	{
		return null;
	}

}
