package com.kirolak;

// Generated 30-nov-2007 8:26:55 by Hibernate Tools 3.2.0.CR1

/**
 * CompetitionTeam generated by hbm2java
 */
public class CompetitionTeam implements java.io.Serializable
{

	private CompetitionTeamId id;

	public CompetitionTeam()
	{
	}

	public CompetitionTeam(CompetitionTeamId id)
	{
		this.id = id;
	}

	public CompetitionTeamId getId()
	{
		return this.id;
	}

	public void setId(CompetitionTeamId id)
	{
		this.id = id;
	}

}
