package com.kirolak;

// Generated 30-nov-2007 8:26:55 by Hibernate Tools 3.2.0.CR1

/**
 * RoundId generated by hbm2java
 */
public class LocalizedId implements java.io.Serializable
{

	private Byte id;
	private String locale;

	public LocalizedId()
	{
	}

	public LocalizedId(Byte id, String locale)
	{
		this.id = id;
		this.locale = locale;
	}

	public Byte getId()
	{
		return this.id;
	}

	public void setId(Byte id)
	{
		this.id = id;
	}

	public boolean equals(Object other)
	{
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LocalizedId))
			return false;
		LocalizedId castOther = (LocalizedId) other;

		return (this.getId() == castOther.getId()) && (this.locale == castOther.getLocale());
	}

	public int hashCode()
	{
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getLocale().charAt(0)+this.getLocale().charAt(1);
		return result;
	}
	
	public String getLocale() {
		return locale;
	}

	public void setLocale(String locale) {
		this.locale = locale;
	}

}
