package com.kirolak;

import java.util.Set;

// Generated 30-nov-2007 8:26:55 by Hibernate Tools 3.2.0.CR1

/**
 * Group generated by hbm2java
 */
public class Group extends KirolakObject
{
	private Stage stage;
	private Set<Team> teams;

	public Group()
	{
		this.id = -1;
	}

	public Group(int id, String name)
	{
		this.id = id;
		this.name = name;
	}

	public Group(int id, Stage stage, String name)
	{
		this.id = id;
		this.stage = stage;
		this.name = name;
	}

	public int getId()
	{
		return this.id;
	}
	
	public void setId(int id)
	{
		this.id = id;
	}

	public Stage getStage()
	{
		return stage;
	}

	public void setStage(Stage stage)
	{
		this.stage = stage;
	}

	public Set<Team> getTeams()
	{
		return teams;
	}

	public void setTeams(Set<Team> teams)
	{
		this.teams = teams;
	}

}
