package com.kirolak;

// Generated 30-nov-2007 8:26:55 by Hibernate Tools 3.2.0.CR1

import java.util.Date;

/**
 * Match generated by hbm2java
 */
public class Match implements java.io.Serializable
{

	private int id;
	private Short roundId;
	private Integer groupId;
	private Integer homeTeamId;
	private Integer visitingTeamId;
	private Short homeTeamScore;
	private Short visitingTeamScore;
	private Byte gameStatus;
	private Date scheduled;

	public Match()
	{
	}

	public Match(int id)
	{
		this.id = id;
	}

	public Match(int id, Short roundId, Integer groupId, Integer homeTeamId, Integer visitingTeamId, Short homeTeamScore, Short visitingTeamScore,
			Byte gameStatus, Date scheduled)
	{
		this.id = id;
		this.roundId = roundId;
		this.groupId = groupId;
		this.homeTeamId = homeTeamId;
		this.visitingTeamId = visitingTeamId;
		this.homeTeamScore = homeTeamScore;
		this.visitingTeamScore = visitingTeamScore;
		this.gameStatus = gameStatus;
		this.scheduled = scheduled;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public Short getRoundId()
	{
		return this.roundId;
	}

	public void setRoundId(Short roundId)
	{
		this.roundId = roundId;
	}

	public Integer getGroupId()
	{
		return this.groupId;
	}

	public void setGroupId(Integer groupId)
	{
		this.groupId = groupId;
	}

	public Integer getHomeTeamId()
	{
		return this.homeTeamId;
	}

	public void setHomeTeamId(Integer homeTeamId)
	{
		this.homeTeamId = homeTeamId;
	}

	public Integer getVisitingTeamId()
	{
		return this.visitingTeamId;
	}

	public void setVisitingTeamId(Integer visitingTeamId)
	{
		this.visitingTeamId = visitingTeamId;
	}

	public Short getHomeTeamScore()
	{
		return this.homeTeamScore;
	}

	public void setHomeTeamScore(Short homeTeamScore)
	{
		this.homeTeamScore = homeTeamScore;
	}

	public Short getVisitingTeamScore()
	{
		return this.visitingTeamScore;
	}

	public void setVisitingTeamScore(Short visitingTeamScore)
	{
		this.visitingTeamScore = visitingTeamScore;
	}

	public Byte getGameStatus()
	{
		return this.gameStatus;
	}

	public void setGameStatus(Byte gameStatus)
	{
		this.gameStatus = gameStatus;
	}

	public Date getScheduled()
	{
		return this.scheduled;
	}

	public void setScheduled(Date scheduled)
	{
		this.scheduled = scheduled;
	}

}
