package com.kirolak;

// Generated 30-nov-2007 8:26:55 by Hibernate Tools 3.2.0.CR1

/**
 * Stage generated by hbm2java
 */
public class Stage implements java.io.Serializable {

	private int id;
	private Integer competitionId;
	private String name;
	private String seoName;
	private Byte type;
	private Byte matches;
	private Byte maxParts;
	private String playOffName;
	private Byte pointsWin;
	private Byte pointsDraw;
	private Byte pointsLoose;

	public Stage() {
	}

	public Stage(int id, String name, String seoName) {
		this.id = id;
		this.name = name;
		this.seoName = seoName;
	}

	public Stage(int id, Integer competitionId, String name, String seoName,
			Byte type, Byte matches, Byte maxParts, String playOffName,
			Byte pointsWin, Byte pointsDraw, Byte pointsLoose) {
		this.id = id;
		this.competitionId = competitionId;
		this.name = name;
		this.seoName = seoName;
		this.type = type;
		this.matches = matches;
		this.maxParts = maxParts;
		this.playOffName = playOffName;
		this.pointsWin = pointsWin;
		this.pointsDraw = pointsDraw;
		this.pointsLoose = pointsLoose;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getCompetitionId() {
		return this.competitionId;
	}

	public void setCompetitionId(Integer competitionId) {
		this.competitionId = competitionId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSeoName() {
		return this.seoName;
	}

	public void setSeoName(String seoName) {
		this.seoName = seoName;
	}

	public Byte getType() {
		return this.type;
	}

	public void setType(Byte type) {
		this.type = type;
	}

	public Byte getMatches() {
		return this.matches;
	}

	public void setMatches(Byte matches) {
		this.matches = matches;
	}

	public Byte getMaxParts() {
		return this.maxParts;
	}

	public void setMaxParts(Byte maxParts) {
		this.maxParts = maxParts;
	}

	public String getPlayOffName() {
		return this.playOffName;
	}

	public void setPlayOffName(String playOffName) {
		this.playOffName = playOffName;
	}

	public Byte getPointsWin() {
		return this.pointsWin;
	}

	public void setPointsWin(Byte pointsWin) {
		this.pointsWin = pointsWin;
	}

	public Byte getPointsDraw() {
		return this.pointsDraw;
	}

	public void setPointsDraw(Byte pointsDraw) {
		this.pointsDraw = pointsDraw;
	}

	public Byte getPointsLoose() {
		return this.pointsLoose;
	}

	public void setPointsLoose(Byte pointsLoose) {
		this.pointsLoose = pointsLoose;
	}

}
