package com.kirolak;


// Generated 30-nov-2007 8:26:55 by Hibernate Tools 3.2.0.CR1

/**
 * Team generated by hbm2java
 */
public class Team extends KirolakObject {

	private String acronym;
	private Sport sport;


	public Team() {
		this.id=-1;
	}
	
	public int getId()
	{
		return this.id;
	}

	public String getAcronym()
	{
		return acronym;
	}

	public void setAcronym(String acronym)
	{
		this.acronym = acronym;
	}


	public Sport getSport()
	{
		return sport;
	}

	public void setSport(Sport sport)
	{
		this.sport = sport;
	}

}
