package com.kirolak;

// Generated 30-nov-2007 8:26:55 by Hibernate Tools 3.2.0.CR1

/**
 * Group generated by hbm2java
 */
public class Group implements java.io.Serializable
{

	private int id;
	private Integer stageId;
	private String name;

	public Group()
	{
	}

	public Group(int id, String name)
	{
		this.id = id;
		this.name = name;
	}

	public Group(int id, Integer stageId, String name)
	{
		this.id = id;
		this.stageId = stageId;
		this.name = name;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public Integer getStageId()
	{
		return this.stageId;
	}

	public void setStageId(Integer stageId)
	{
		this.stageId = stageId;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

}
