package com.kirolak;

// Generated 30-nov-2007 8:26:55 by Hibernate Tools 3.2.0.CR1

/**
 * StandingId generated by hbm2java
 */
public class StandingId implements java.io.Serializable
{

	private int teamId;
	private short roundId;
	private int groupId;

	public StandingId()
	{
	}

	public StandingId(int teamId, short roundId, int groupId)
	{
		this.teamId = teamId;
		this.roundId = roundId;
		this.groupId = groupId;
	}

	public int getTeamId()
	{
		return this.teamId;
	}

	public void setTeamId(int teamId)
	{
		this.teamId = teamId;
	}

	public short getRoundId()
	{
		return this.roundId;
	}

	public void setRoundId(short roundId)
	{
		this.roundId = roundId;
	}

	public int getGroupId()
	{
		return this.groupId;
	}

	public void setGroupId(int groupId)
	{
		this.groupId = groupId;
	}

	public boolean equals(Object other)
	{
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StandingId))
			return false;
		StandingId castOther = (StandingId) other;

		return (this.getTeamId() == castOther.getTeamId()) && (this.getRoundId() == castOther.getRoundId())
				&& (this.getGroupId() == castOther.getGroupId());
	}

	public int hashCode()
	{
		int result = 17;

		result = 37 * result + this.getTeamId();
		result = 37 * result + this.getRoundId();
		result = 37 * result + this.getGroupId();
		return result;
	}

}
