package com.kirolak;

// Generated 30-nov-2007 8:26:55 by Hibernate Tools 3.2.0.CR1

/**
 * GroupTeam generated by hbm2java
 */
public class GroupTeam implements java.io.Serializable
{

	private GroupTeamId id;

	public GroupTeam()
	{
	}

	public GroupTeam(GroupTeamId id)
	{
		this.id = id;
	}

	public GroupTeamId getId()
	{
		return this.id;
	}

	public void setId(GroupTeamId id)
	{
		this.id = id;
	}

}
