package com.kirolak;

// Generated 30-nov-2007 8:26:55 by Hibernate Tools 3.2.0.CR1

/**
 * Sport generated by hbm2java
 */
public class Sport implements java.io.Serializable
{

	private short id;
	private String name;
	private String seoName;
	private Byte scoreMode;
	private String partName;
	private Byte maxParts;
	private String playOffName;
	private Byte pointsWin;
	private Byte pointsDraw;
	private Byte pointsLoose;

	public Sport()
	{
		this.id = -1;
	}

	public Sport(short id)
	{
		this.id = -1;
	}

	public Sport(short id, String name, String seoName, Byte scoreMode, String partName, Byte maxParts, String playOffName, Byte pointsWin,
			Byte pointsDraw, Byte pointsLoose)
	{
		this.id = id;
		this.name = name;
		this.seoName = seoName;
		this.scoreMode = scoreMode;
		this.partName = partName;
		this.maxParts = maxParts;
		this.playOffName = playOffName;
		this.pointsWin = pointsWin;
		this.pointsDraw = pointsDraw;
		this.pointsLoose = pointsLoose;
	}

	public short getId()
	{
		return this.id;
	}

	public void setId(short id)
	{
		this.id = id;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getSeoName()
	{
		return this.seoName;
	}

	public void setSeoName(String seoName)
	{
		this.seoName = seoName;
	}

	public Byte getScoreMode()
	{
		return this.scoreMode;
	}

	public void setScoreMode(Byte scoreMode)
	{
		this.scoreMode = scoreMode;
	}

	public String getPartName()
	{
		return this.partName;
	}

	public void setPartName(String partName)
	{
		this.partName = partName;
	}

	public Byte getMaxParts()
	{
		return this.maxParts;
	}

	public void setMaxParts(Byte maxParts)
	{
		this.maxParts = maxParts;
	}

	public String getPlayOffName()
	{
		return this.playOffName;
	}

	public void setPlayOffName(String playOffName)
	{
		this.playOffName = playOffName;
	}

	public Byte getPointsWin()
	{
		return this.pointsWin;
	}

	public void setPointsWin(Byte pointsWin)
	{
		this.pointsWin = pointsWin;
	}

	public Byte getPointsDraw()
	{
		return this.pointsDraw;
	}

	public void setPointsDraw(Byte pointsDraw)
	{
		this.pointsDraw = pointsDraw;
	}

	public Byte getPointsLoose()
	{
		return this.pointsLoose;
	}

	public void setPointsLoose(Byte pointsLoose)
	{
		this.pointsLoose = pointsLoose;
	}

}
