package com.kirolak;

// Generated 30-nov-2007 8:26:55 by Hibernate Tools 3.2.0.CR1

/**
 * Team generated by hbm2java
 */
public class Team implements java.io.Serializable {

	private int id;
	private Short sportId;
	private String name;
	private String seoName;

	public Team() {
	}

	public Team(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public Team(int id, Short sportId, String name) {
		this.id = id;
		this.sportId = sportId;
		this.name = name;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Short getSportId() {
		return this.sportId;
	}

	public void setSportId(Short sportId) {
		this.sportId = sportId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	public String getSeoName() {
		return this.seoName;
	}

	public void setSeoName(String seoName) {
		this.seoName = seoName;
	}

}
