package com.kirolak;

import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;


// Generated 30-nov-2007 8:26:55 by Hibernate Tools 3.2.0.CR1

/**
 * Group generated by hbm2java
 */
public class Group extends KirolakObject
{
	protected Stage stage;
	protected Set<Team> teams = new HashSet<Team>();
	private Short lastPlayedRound;

	public Group()
	{
		this.id = -1;
	}

	public Group(int id, String name)
	{
		this.id = id;
		this.name = name;
	}

	public Group(int id, Stage stage, String name)
	{
		this.id = id;
		this.stage = stage;
		this.name = name;
	}

	public int getId()
	{
		return this.id;
	}
	
	public void setId(int id)
	{
		this.id = id;
	}

	public Stage getStage()
	{
		return stage;
	}

	public void setStage(Stage stage)
	{
		this.stage = stage;
	}

	public Set<Team> getTeams()
	{
		return teams;
	}

	public void setTeams(Set<Team> teams)
	{
		this.teams = teams;
	}
	
	public String getTeamNames()
	{
		String returnValue = "";
		Iterator<Team> iterator = getTeams().iterator();
		if(iterator.hasNext())
		{
			returnValue = iterator.next().getName();
			while(iterator.hasNext())
			{
				returnValue += ", " + iterator.next().getName();
			}
		}
		return returnValue;
	}
	
	

	public Short getLastPlayedRound()
	{
		return lastPlayedRound;
	}

	public void setLastPlayedRound(Short lastPlayedRound)
	{
		if(lastPlayedRound == null)
		{
			lastPlayedRound = 0;
		}
		this.lastPlayedRound = lastPlayedRound;
	}

}
